import { EmailCapture } from '@/components/EmailCapture';
import Link from 'next/link';

export default function AIUXChecklistPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-24">
      <header className="mb-16 text-center">
        <h1 className="text-4xl md:text-5xl font-medium tracking-tight mb-6">Is your AI-built product missing UX clarity?</h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          AI tools can build functional products in hours, but they often miss the structure, hierarchy, and guidance new users need.
        </p>
      </header>

      <section className="bg-surface p-8 md:p-12 rounded-2xl mb-16">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div>
            <h2 className="text-2xl font-medium mb-4">Get the free 10-point checklist.</h2>
            <p className="text-gray-600 mb-6">
              Learn the most common UX mistakes AI generators make and how to fix them before showing your MVP to users or investors.
            </p>
            <EmailCapture />
          </div>
          <div className="hidden md:flex justify-center">
            <div className="w-48 h-64 bg-white shadow-sm border border-gray-100 rounded-xl p-4 rotate-3">
              <div className="w-full h-4 bg-gray-100 rounded mb-4"></div>
              <div className="w-3/4 h-3 bg-gray-100 rounded mb-2"></div>
              <div className="w-5/6 h-3 bg-gray-100 rounded mb-6"></div>
              <div className="w-full h-8 bg-brand-50 rounded mb-4"></div>
              <div className="w-full h-8 bg-gray-50 rounded mb-4"></div>
              <div className="w-full h-8 bg-gray-50 rounded"></div>
            </div>
          </div>
        </div>
      </section>

      <section className="prose prose-lg text-gray-600 mx-auto">
        <h3 className="text-xl font-medium text-foreground">What's inside?</h3>
        <ul>
          <li>Why AI tools treat every button as a primary action (and how to fix your hierarchy).</li>
          <li>How to design empty states that actually help users start.</li>
          <li>Why onboarding flows generated by AI often confuse users.</li>
          <li>Simple ways to make your generated interface feel premium and trustworthy.</li>
        </ul>
      </section>

      <div className="mt-20 text-center">
        <p className="text-gray-500 mb-4">Need immediate help with your prototype?</p>
        <Link href="/services/prototyping" className="text-brand-500 font-medium hover:text-brand-900 transition-colors">
          Explore our Prototyping service →
        </Link>
      </div>
    </div>
  );
}